application: blockly-games
version: 1
runtime: python27
api_version: 1
threadsafe: no
# App Engine default is 10m.
default_expiration: "12h"

handlers:
# Storage API.
- url: /storage
  script: storage.py
  secure: always
- url: /storage\.js
  static_files: storage.js
  upload: storage\.js
  secure: always

# Index page.
- url: /
  static_files: index.html
  upload: index\.html
  secure: always
- url: /index/
  static_dir: index
  secure: always

# About page.
- url: /about
  static_files: about.html
  upload: about\.html
  secure: always

# Debug page.
- url: /debug
  static_files: debug.html
  upload: debug\.html
  secure: always

# Bird app.
- url: /bird
  static_files: bird.html
  upload: bird\.html
  secure: always
- url: /bird/
  static_dir: bird
  secure: always

# Maze app.
- url: /maze
  static_files: maze.html
  upload: maze\.html
  secure: always
- url: /maze/
  static_dir: maze
  secure: always

# Movie app.
- url: /movie
  static_files: movie.html
  upload: movie\.html
  secure: always
- url: /movie/
  static_dir: movie
  secure: always
- url: /movie-reddit
  script: reddit.py
  secure: always

# Puzzle app.
- url: /puzzle
  static_files: puzzle.html
  upload: puzzle\.html
  secure: always
- url: /puzzle/
  static_dir: puzzle
  secure: always

# Turtle app.
- url: /turtle
  static_files: turtle.html
  upload: turtle\.html
  secure: always
- url: /turtle/
  static_dir: turtle
  secure: always
- url: /turtle-reddit
  script: reddit.py
  secure: always

# Pond apps.
- url: /pond-tutor
  static_files: pond-tutor.html
  upload: pond-tutor\.html
  secure: always
- url: /pond-duck
  static_files: pond-duck.html
  upload: pond-duck\.html
  secure: always
- url: /pond/
  static_dir: pond
  secure: always

# Genetics app.
- url: /genetics
  static_files: genetics.html
  upload: genetics\.html
  secure: always
- url: /genetics/
  static_dir: genetics
  secure: always

# Shared files.
- url: /common
  static_dir: common
  secure: always
- url: /js
  static_dir: js
  secure: always
- url: /generated
  static_dir: generated
  secure: always
- url: /third-party/
  static_dir: third-party
  secure: always
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico
  secure: always
  expiration: "30d"
- url: /apple-touch-icon\.png
  static_files: apple-touch-icon.png
  upload: apple-touch-icon\.png
  secure: always
  expiration: "30d"
- url: /robots\.txt
  static_files: robots.txt
  upload: robots\.txt
  secure: always
- url: /thumb
  script: reddit.py
  secure: always

# Source files and uncompiled versions.
skip_files:
# App Engine default patterns.
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$
# Custom skip patterns.
- ^\w+/sources/.*$
- ^third-party/blockly/appengine/.*$
- ^third-party/blockly/demos/.*$
- ^third-party/blockly/generators/dart.*$
- ^third-party/blockly/generators/lua.*$
- ^third-party/blockly/generators/php.*$
- ^third-party/blockly/generators/python.*$
- ^third-party/blockly/i18n/.*$
- ^third-party/blockly/msg/json/.*$
- ^third-party/blockly/tests/.*$
- ^third-party/third_party_goog/.*$
- ^third-party/ace/snippets/.*$
- ^third-party/JS-Interpreter/[^c].*$  # Only serve compiled.js.
- ^.+\.soy$
